"""fresh initial migration

Revision ID: 184e11ea9564
Revises: 
Create Date: 2025-07-08 04:15:08.044872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184e11ea9564'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subscription_plan', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('raw_text_encrypted', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('job_number', sa.String(length=100), nullable=True),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_created', 'contracts', ['company_id', 'created_at'], unique=False)
    op.create_index('idx_company_job', 'contracts', ['company_id', 'job_number'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('contract_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('agreement_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('retainage_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('insurance_required', sa.Boolean(), nullable=True),
    sa.Column('bond_required', sa.Boolean(), nullable=True),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('contractor_name_encrypted', sa.String(), nullable=True),
    sa.Column('subcontractor_name_encrypted', sa.String(), nullable=True),
    sa.Column('owner_name_encrypted', sa.String(), nullable=True),
    sa.Column('contract_name_encrypted', sa.String(), nullable=True),
    sa.Column('project_location_encrypted', sa.String(), nullable=True),
    sa.Column('work_description_encrypted', sa.Text(), nullable=True),
    sa.Column('payment_terms_encrypted', sa.Text(), nullable=True),
    sa.Column('insurance_amount_encrypted', sa.String(), nullable=True),
    sa.Column('bond_amount_encrypted', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_analysis_id'), 'contract_analysis', ['id'], unique=False)
    op.create_table('directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('importance', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('is_main_contract', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('main_parties', sa.Text(), nullable=True),
    sa.Column('contract_value_text', sa.String(), nullable=True),
    sa.Column('project_info', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=30), nullable=True),
    sa.Column('classification_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directories_contract_id'), 'directories', ['contract_id'], unique=False)
    op.create_index(op.f('ix_directories_id'), 'directories', ['id'], unique=False)
    op.create_index(op.f('ix_directories_importance'), 'directories', ['importance'], unique=False)
    op.create_index(op.f('ix_directories_is_main_contract'), 'directories', ['is_main_contract'], unique=False)
    op.create_table('wip_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('job_number', sa.String(), nullable=True),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('contract_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wip_entries')
    op.drop_index(op.f('ix_directories_is_main_contract'), table_name='directories')
    op.drop_index(op.f('ix_directories_importance'), table_name='directories')
    op.drop_index(op.f('ix_directories_id'), table_name='directories')
    op.drop_index(op.f('ix_directories_contract_id'), table_name='directories')
    op.drop_table('directories')
    op.drop_index(op.f('ix_contract_analysis_id'), table_name='contract_analysis')
    op.drop_table('contract_analysis')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index('idx_company_job', table_name='contracts')
    op.drop_index('idx_company_created', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
