"""add_contract_intelligence_table

Revision ID: 51e8e681a31c
Revises: d38bae7c8b33
Create Date: 2025-07-06 20:41:39.484590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e8e681a31c'
down_revision: Union[str, None] = 'd38bae7c8b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('importance', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('is_main_contract', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('main_parties', sa.Text(), nullable=True),
    sa.Column('contract_value_text', sa.String(), nullable=True),
    sa.Column('project_info', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=30), nullable=True),
    sa.Column('classification_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_intelligence_contract_id'), 'contract_intelligence', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_intelligence_id'), 'contract_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_contract_intelligence_importance'), 'contract_intelligence', ['importance'], unique=False)
    op.create_index(op.f('ix_contract_intelligence_is_main_contract'), 'contract_intelligence', ['is_main_contract'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_intelligence_is_main_contract'), table_name='contract_intelligence')
    op.drop_index(op.f('ix_contract_intelligence_importance'), table_name='contract_intelligence')
    op.drop_index(op.f('ix_contract_intelligence_id'), table_name='contract_intelligence')
    op.drop_index(op.f('ix_contract_intelligence_contract_id'), table_name='contract_intelligence')
    op.drop_table('contract_intelligence')
    # ### end Alembic commands ###
