"""separate contract storage and analysis tables

Revision ID: 5476805b10b8
Revises: a2b149a84698
Create Date: 2025-07-06 09:19:10.409364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5476805b10b8'
down_revision: Union[str, None] = 'a2b149a84698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'contract_name')
    op.drop_column('contracts', 'contract_value')
    op.drop_column('contracts', 'contract_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('contract_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('contract_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('contract_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
