"""add encryption columns for sensitive data

Revision ID: 58ba1604aa78
Revises: 
Create Date: 2025-07-06 10:13:15.171341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ba1604aa78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('contract_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('contract_name', sa.String(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.Column('subcontractor_name', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('agreement_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('project_location', sa.String(), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('retainage_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('insurance_required', sa.Boolean(), nullable=True),
    sa.Column('bond_required', sa.Boolean(), nullable=True),
    sa.Column('insurance_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bond_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('contractor_name_encrypted', sa.String(), nullable=True),
    sa.Column('subcontractor_name_encrypted', sa.String(), nullable=True),
    sa.Column('owner_name_encrypted', sa.String(), nullable=True),
    sa.Column('contract_name_encrypted', sa.String(), nullable=True),
    sa.Column('project_location_encrypted', sa.String(), nullable=True),
    sa.Column('work_description_encrypted', sa.Text(), nullable=True),
    sa.Column('payment_terms_encrypted', sa.Text(), nullable=True),
    sa.Column('insurance_amount_encrypted', sa.String(), nullable=True),
    sa.Column('bond_amount_encrypted', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_analysis_id'), 'contract_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_analysis_id'), table_name='contract_analysis')
    op.drop_table('contract_analysis')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
