"""add wip_entries table

Revision ID: 898ef5c08b99
Revises: 9fc92549e611
Create Date: 2025-07-07 20:07:42.410415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898ef5c08b99'
down_revision: Union[str, None] = '9fc92549e611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wip_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('job_number', sa.String(), nullable=True),
    sa.Column('business_field', sa.String(), nullable=True),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('contract_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('original_job_number', sa.String(), nullable=True),
    sa.Column('original_job_name', sa.String(), nullable=True),
    sa.Column('original_contract_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('has_deviations', sa.Boolean(), nullable=True),
    sa.Column('deviation_fields', sa.Text(), nullable=True),
    sa.Column('deviation_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_deviation_check', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wip_entries')
    # ### end Alembic commands ###
