"""Simplify contract table

Revision ID: a2b149a84698
Revises: c3340e1288a4
Create Date: 2025-07-04 08:32:18.017004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2b149a84698'
down_revision: Union[str, None] = 'c3340e1288a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('contract_number', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('contract_name', sa.String(), nullable=True))
    op.drop_column('contracts', 'project_location')
    op.drop_column('contracts', 'contract_date')
    op.drop_column('contracts', 'project_name')
    op.drop_column('contracts', 'start_date')
    op.drop_column('contracts', 'work_description')
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'subcontractor_name')
    op.drop_column('contracts', 'file_path')
    op.drop_column('contracts', 'extraction_confidence')
    op.drop_column('contracts', 'end_date')
    op.drop_column('contracts', 'manual_review_needed')
    op.drop_column('contracts', 'gov_contract_number')
    op.drop_column('contracts', 'contractor_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('contractor_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('gov_contract_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('manual_review_needed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('extraction_confidence', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('subcontractor_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('work_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('contract_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('project_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contracts', 'contract_name')
    op.drop_column('contracts', 'contract_number')
    # ### end Alembic commands ###
