"""add encryption columns for sensitive data

Revision ID: c004eb22d625
Revises: 58ba1604aa78
Create Date: 2025-07-06 10:18:41.113813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c004eb22d625'
down_revision: Union[str, None] = '58ba1604aa78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('raw_text_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'raw_text_encrypted')
    # ### end Alembic commands ###
