"""add new AI Analysis table

Revision ID: fe3bbd19663d
Revises: 5476805b10b8
Create Date: 2025-07-06 09:23:00.271896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3bbd19663d'
down_revision: Union[str, None] = '5476805b10b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('contract_name', sa.String(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.Column('subcontractor_name', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('agreement_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('project_location', sa.String(), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('retainage_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('insurance_required', sa.Boolean(), nullable=True),
    sa.Column('bond_required', sa.Boolean(), nullable=True),
    sa.Column('insurance_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bond_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_analyses_id'), 'contract_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_analyses_id'), table_name='contract_analyses')
    op.drop_table('contract_analyses')
    # ### end Alembic commands ###
