"""Add WIP table with job number and project name

Revision ID: a960217e6f06
Revises: e253c80b41f2
Create Date: 2025-08-17 16:52:41.869862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a960217e6f06'
down_revision: Union[str, Sequence[str], None] = 'e253c80b41f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_number', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wip_id'), 'wip', ['id'], unique=False)
    op.create_index(op.f('ix_wip_job_number'), 'wip', ['job_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wip_job_number'), table_name='wip')
    op.drop_index(op.f('ix_wip_id'), table_name='wip')
    op.drop_table('wip')
    # ### end Alembic commands ###
